tap "1password/tap"
tap "anchore/grype"
tap "arttor/tap"
tap "aylei/tap"
tap "bufbuild/buf"
tap "buo/cask-upgrade"
tap "cloudflare/cloudflare"
tap "cue-lang/tap"
tap "cuelang/tap"
tap "dagger/tap"
tap "danielfoehrkn/switch"
tap "derailed/k9s"
tap "felixkratz/formulae"
tap "fluxcd/tap"
tap "geldata/tap", "https://github.com/geldata/homebrew-tap.git"
tap "googlecontainertools/kpt", "https://github.com/kptdev/kpt.git"
tap "homeport/tap"
tap "jzelinskie/faq"
tap "kubeshark/kubeshark"
tap "norwoodj/tap"
tap "secureauthcorp/tap", "https://github.com/SecureAuthCorp/homebrew-tap.git"
tap "turbot/tap"
# TIFF library and utilities
brew "libtiff"
# Color management engine supporting ICC profiles
brew "little-cms2"
# Image format providing lossless and lossy compression for web images
brew "webp"
# New file format for still image compression
brew "jpeg-xl"
# Codec library for encoding and decoding AV1 video streams
brew "aom"
# GitOps Continuous Delivery for Kubernetes
brew "argocd"
# Utility to check whether MAC addresses are already taken on a LAN
brew "arping"
# Record and share terminal sessions
brew "asciinema"
# Distributed revision control system
brew "git"
# Extendable version manager with support for Ruby, Node.js, Erlang & more
brew "asdf"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Securely store and access AWS credentials in development environments
brew "aws-vault"
# Official Amazon AWS command-line interface
brew "awscli"
# Microsoft Azure CLI 2.0
brew "azure-cli"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# C library of Git core methods that is re-entrant and linkable
brew "libgit2"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Software library to render fonts
brew "freetype"
# Core application library for C
brew "glib"
# Multi-platform, multi-architecture disassembly framework
brew "capstone"
# C parser in Python
brew "pycparser"
# C Foreign Function Interface for Python
brew "cffi"
# CLI to install, manage & troubleshoot Kubernetes clusters running Cilium
brew "cilium-cli"
# Cloudflare Tunnel client (formerly Argo Tunnel)
brew "cloudflared"
# Cross-platform make
brew "cmake"
# Linux virtual machines
brew "lima"
# Container runtimes on MacOS (and Linux) with minimal setup
brew "colima"
# Container Signing
brew "cosign"
# Cryptographic recipes and primitives for Python
brew "cryptography"
# Reimplementation of ctags(1)
brew "ctags"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# File comparison utilities
brew "diffutils"
# Load/unload environment variables based on $PWD
brew "direnv"
# Pack, ship and run any application as a lightweight container
brew "docker"
# Docker CLI plugin for extended build capabilities with BuildKit
brew "docker-buildx"
# Isolated development environments using Docker
brew "docker-compose"
# Platform keystore credential helper for Docker
brew "docker-credential-helper"
# Text processing system for reStructuredText
brew "docutils"
# CLI utility to build and manage a PKI CA
brew "easy-rsa"
# Spellchecker wrapping library
brew "enchant"
# Program that can automate interactive applications
brew "expect"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Collection of GNU find, xargs, and locate
brew "findutils"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU awk utility
brew "gawk"
# GNU compiler collection
brew "gcc"
# Toolkit for image loading and pixel buffer manipulation
brew "gdk-pixbuf"
# GitHub command-line tool
brew "gh"
# OpenType text shaping engine
brew "harfbuzz"
# Framework for layout and rendering of i18n text
brew "pango"
# Interpreter for PostScript and PDF
brew "ghostscript"
# Automatic git commit --fixup
brew "git-absorb"
# High-velocity, monorepo-scale workflow for Git
brew "git-branchless"
# Git extension for versioning large files
brew "git-lfs"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# GNU version of the tar archiving utility
brew "gnu-tar"
# Validating, recursive, caching DNS resolver
brew "unbound"
# GNU Transport Layer Security (TLS) Library
brew "gnutls"
# GNU Privacy Guard (OpenPGP)
brew "gnupg"
# Go implementation of configuration language for defining JSON data
brew "go-jsonnet"
# Generate introspection data for GObject libraries
brew "gobject-introspection"
# Fast linters runner for Go
brew "golangci-lint"
# Library access to GnuPG
brew "gpgme"
# Image manipulation
brew "netpbm"
# Interpreted, interactive, object-oriented programming language
brew "python@3.12"
# Library to render SVG files using Cairo
brew "librsvg"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# GNU grep, egrep and fgrep
brew "grep"
# Utilities for manipulating PostScript documents
brew "psutils"
# GNU troff text-formatting system
brew "groff"
# Make JSON greppable
brew "gron"
# Like cURL, but for gRPC
brew "grpcurl"
# Vulnerability scanner for container images and filesystems
brew "grype"
# Tool for glamorous shell scripts
brew "gum"
# Popular GNU data compression program
brew "gzip"
# Kubernetes package manager
brew "helm"
# Deploy Kubernetes Helm Charts
brew "helmfile"
# Improved top (interactive process viewer)
brew "htop"
# Add GitHub support to git on the command-line
brew "hub"
# Tools and libraries to manipulate images in select formats
brew "imagemagick"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Package manager for Jsonnet
brew "jsonnet-bundler"
# Helps you navigate your file system faster by learning your habits
brew "jump"
# Little helper to run CNCF's k3s in Docker
brew "k3d"
# Kubernetes CLI To Manage Your Clusters In Style!
brew "k9s"
# Network authentication protocol
brew "krb5"
# Kubernetes command-line interface
brew "kubernetes-cli"
# Package manager for kubectl plugins
brew "krew"
# Kubernetes prompt info for bash and zsh
brew "kube-ps1"
# Kubernetes object analysis recommendations for improved reliability and security
brew "kube-score"
# Colorize your kubectl output
brew "kubecolor"
# FAST Kubernetes manifests validator, with support for Custom Resources!
brew "kubeconform"
# Easily check your clusters for use of deprecated APIs
brew "kubent"
# Kubernetes testing according to Hardening Guidance by NSA and CISA
brew "kubescape"
# Kubernetes controller and tool for one-way encrypted Secrets
brew "kubeseal"
# Template-free customization of Kubernetes YAML manifests
brew "kustomize"
# C virtualization API
brew "libvirt"
# Next-gen compiler infrastructure
brew "llvm"
# Run LogQL queries against a Loki server
brew "logcli"
# Text-to-HTML conversion tool
brew "markdown"
# Mac App Store command-line interface
brew "mas"
# Development kit for the Java programming language
brew "openjdk"
# Java-based project management
brew "maven"
# Fast and user friendly build system
brew "meson"
# Run a Kubernetes cluster locally
brew "minikube"
# Replacement for ls, cp and other commands for object storage
brew "minio-mc"
# Polyglot runtime manager (asdf rust clone)
brew "mise", link: false
# Simple tool to make locally trusted development certificates
brew "mkcert"
# MongoDB Shell to connect, configure, query, and work with your MongoDB database
brew "mongosh"
# Collection of tools that nobody wrote when UNIX was young
brew "moreutils"
# Library for a binary-based efficient data interchange format
brew "msgpack"
# 'traceroute' and 'ping' in a single tool
brew "mtr"
# NCurses Disk Usage
brew "ncdu"
# Statically typed compiled systems programming language
brew "nim"
# Port scanning utility for large networks
brew "nmap"
# Manage multiple Node.js versions
brew "nvm"
# User-friendly CLI for OAuth2
brew "oauth2c"
# Create, run, and share large language models (LLMs)
brew "ollama", restart_service: :changed
# 7-Zip (high compression file archiver) implementation
brew "p7zip"
# Swiss-army knife of markup format conversion
brew "pandoc"
# Paragraph reflow for email
brew "par"
# Shell command parallelization utility
brew "parallel", link: false
# Small collection of programs that operate on patch files
brew "patchutils"
# Pinentry for GPG on Mac
brew "pinentry-mac"
# Object-relational database system
brew "postgresql@14"
# Framework for managing multi-language pre-commit hooks
brew "pre-commit"
# Service monitoring system and time series database
brew "prometheus"
# Protocol buffers (Google's data interchange format)
brew "protobuf"
# Show ps output as a tree
brew "pstree"
# Monitor data's progress through a pipe
brew "pv"
# Password generator
brew "pwgen"
# Interpreted, interactive, object-oriented programming language
brew "python@3.10"
# Interpreted, interactive, object-oriented programming language
brew "python@3.11"
# Interpreted, interactive, object-oriented programming language
brew "python@3.9"
# Generic machine emulator and virtualizer
brew "qemu"
# Persistent key-value database, with built-in net interface
brew "redis"
# Perl-powered file rename script with many helpful built-ins
brew "rename"
# Repeat a command until the command succeeds
brew "retry"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Utility that provides fast incremental file transfer
brew "rsync"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Autoformat shell script source code
brew "shfmt"
# Advanced console-based IP subnet calculator
brew "sipcalc"
# Work with remote images registries
brew "skopeo"
# SOcket CAT: netcat on steroids
brew "socat"
# Proxy server that works as a poor man's VPN
brew "sshuttle"
# SSLv3/TLS network protocol analyzer
brew "ssldump"
# Tail multiple Kubernetes pods & their containers
brew "stern"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# CLI for generating a Software Bill of Materials from container images
brew "syft"
# Flexible, reusable and concise configuration for Kubernetes using Jsonnet
brew "tanka"
# Command-line packet analyzer
brew "tcpdump"
# Tool to generate documentation from Terraform modules
brew "terraform-docs"
# Define your dev environment as code. For microservice apps on Kubernetes
brew "tilt"
# Terminal multiplexer
brew "tmux"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Vulnerability scanner for container images, file systems, and Git repos
brew "trivy"
# ODBC 3 connectivity for UNIX
brew "unixodbc"
# Extremely fast Python package installer and resolver, written in Rust
brew "uv"
# Syntax-aware linter for prose
brew "vale"
# Modern watch command
brew "viddy"
# Tool for creating isolated virtual python environments
brew "virtualenv"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Internet file retriever
brew "wget"
# Linter for YAML files
brew "yamllint"
# View colored diff with side by side and auto pager support
brew "ydiff"
# Process YAML, JSON, XML, CSV and properties documents from the CLI
brew "yq"
# UNIX shell (command interpreter)
brew "zsh"
# Password manager that keeps all passwords secure behind one password
cask "1password"
# Command-line interface for 1Password
cask "1password-cli"
# Tool to customise input devices and automate computer systems
cask "bettertouchtool"
# Column-oriented database management system
cask "clickhouse"
# Semantic code analysis engine
cask "codeql"
# Monitor filesystem activity
cask "filemonitor"
cask "font-fira-code-nerd-font"
cask "font-inconsolata-for-powerline"
cask "font-inconsolata-nerd-font"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
# Set of tools to manage resources and applications hosted on Google Cloud
cask "gcloud-cli"
# GPU-based terminal emulator
cask "kitty"
# Open-source cross-platform alternative to AirDrop
cask "localsend"
# SQL powered operating system instrumentation and analytics
cask "osquery"
# Monitor process activity
cask "processmonitor"
# Plugin for AWS CLI to start and end sessions that connect to managed instances
cask "session-manager-plugin"
# Team communication and collaboration software
cask "slack"
# Multimedia player
cask "vlc"
# Network protocol analyzer
cask "wireshark-app"
# Video communication and virtual meeting platform
cask "zoom"
mas "1Password for Safari", id: 1569813296
mas "AdGuard for Safari", id: 1440147259
mas "Amphetamine", id: 937984704
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Tailscale", id: 1475387142
mas "Userscripts", id: 1463298887
go "github.com/rhysd/actionlint/cmd/actionlint"
go "github.com/google/addlicense"
go "github.com/air-verse/air"
go "github.com/chancez/ar-go"
go "github.com/klauspost/asmfmt/cmd/asmfmt"
go "github.com/isovalent/athena/cmd/athena"
go "golang.org/x/perf/cmd/benchstat"
go "github.com/unknwon/bra"
go "github.com/cloudflare/cfssl/cmd/cfssljson"
go "go.opentelemetry.io/build-tools/checkdoc"
go "k8s.io/code-generator/cmd/client-gen"
go "github.com/spf13/cobra-cli"
go "github.com/Mirantis/cri-dockerd"
go "go.opentelemetry.io/build-tools/crosslink"
go "k8s.io/code-generator/cmd/deepcopy-gen"
go "k8s.io/code-generator/cmd/defaulter-gen"
go "golang.org/x/tools/cmd/digraph"
go "github.com/go-delve/delve/cmd/dlv"
go "github.com/kisielk/errcheck"
go "github.com/davidrjenni/reftools/cmd/fillstruct"
go "github.com/tcnksm/ghr"
go "github.com/onsi/ginkgo/v2/ginkgo"
go "golang.org/x/review/git-codereview"
go "github.com/badjware/gitforgefs"
go "golang.org/x/tools/cmd/go-contrib-init"
go "github.com/jstemmer/go-junit-report"
go "github.com/google/go-licenses"
go "github.com/chancez/go-to-protobuf"
go "github.com/loov/goda"
go "github.com/rogpeppe/godef"
go "github.com/Bhupesh-V/godeping"
go "github.com/NonLogicalDev/gofancyimports/cmd/gofancyimports"
go "mvdan.cc/gofumpt"
go "golang.org/x/tools/cmd/goimports"
go "sigs.k8s.io/kube-api-linter/cmd/golangci-lint-kube-api-linter"
go "golang.org/x/lint/golint"
go "github.com/fatih/gomodifytags"
go "golang.org/x/tools/gopls"
go "github.com/google/gops"
go "github.com/jstemmer/gotags"
go "gotest.tools/gotestsum"
go "golang.org/x/vuln/cmd/govulncheck"
go "github.com/grpc-ecosystem/grpc-health-probe"
go "golang.org/x/tools/cmd/guru"
go "github.com/cilium/hubble/enterprise/hubble"
go "github.com/koron/iferr"
go "github.com/pavius/impi/cmd/impi"
go "github.com/josharian/impl"
go "github.com/nikolaydubina/import-graph"
go "k8s.io/code-generator/cmd/informer-gen"
go "github.com/isovalent/glibsm/go/iso"
go "go.opentelemetry.io/build-tools/issuegenerator"
go "github.com/nikolaydubina/jsonl-graph"
go "github.com/aws/karpenter/tools/karpenter-convert/cmd/karpenter-convert"
go "honnef.co/go/tools/cmd/keyify"
go "github.com/cilium/linters"
go "k8s.io/code-generator/cmd/lister-gen"
go "github.com/magefile/mage"
go "github.com/client9/misspell/cmd/misspell"
go "github.com/marwan-at-work/mod/cmd/mod"
go "github.com/fatih/motion"
go "go.opentelemetry.io/build-tools/multimod"
go "github.com/rancher-sandbox/rancher-desktop/src/go/nerdctl-stub"
go "github.com/deepmap/oapi-codegen/cmd/oapi-codegen"
go "github.com/catilac/plistwatch"
go "github.com/grafana/plugin-validator/pkg/cmd/plugincheck"
go "github.com/jcchavezs/porto/cmd/porto"
go "github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc"
go "google.golang.org/protobuf/cmd/protoc-gen-go"
go "google.golang.org/grpc/cmd/protoc-gen-go-grpc"
go "github.com/mitchellh/protoc-gen-go-json"
go "github.com/mgechev/revive"
go "honnef.co/go/tools/cmd/staticcheck"
go "github.com/go-swagger/go-swagger/cmd/swagger"
go "github.com/google/wire/cmd/wire"
go "github.com/rancher-sandbox/rancher-desktop/src/go/wsl-helper"
cargo "cross"
krew "minio"
krew "sniff"
krew "tree"
npm "corepack"
