[tools]
# you can set these with `rtx use -g`
node = ['lts', '20', '19', '18', '17', '16']
python = ['3.10', '2.7']
golang = '1.20'
terraform = '1.4.6'
java = '20'
kubectl = '1.24'
ruby = '3.1'
neovim = '0.8'
rust = 'stable'

[settings]
legacy_version_file = true
asdf_compat = true
