dialect = "us"
timezone = "local"
search_mode = "fuzzy"
filter_mode = "global"
workspaces = true
style = "auto"
invert = true
show_preview = true
show_numeric_shortcuts = false
# history_format = "{time}\t{command}\t{duration}"
enter_accept = false
keymap_mode = "vim-insert"
keymap_cursor = { emacs = "blink-block", vim_insert = "blink-block", vim_normal = "steady-block" }
prefers_reduced_motion = true

[keys]
scroll_exits = false
exit_past_line_start = false
accept_past_line_end = false

[sync]
records = true

[search]
filters = [ "workspace", "directory", "global", "host", "session" ]

[ui]
columns = ["duration", "time", "command"]
