#!/bin/bash

function hc() {
    herbstclient "$@"
}

hc emit_hook reload

xscreensaver -no-splash &
xsetroot -solid black
xcompmgr -C &
~/.config/herbstluftwm/wallpaper.sh &

# colors
hc set frame_border_active_color '#6c71c4'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#000000'
hc set frame_bg_active_color '#222222'
hc set frame_border_width 3
hc set frame_inner_border_width 1
hc set frame_active_opacity 60
hc set frame_normal_opacity 10

hc set window_border_width 2
hc set window_border_inner_width 1
hc set window_border_normal_color '#454545'
hc set window_border_active_color '#1793D1'
hc set always_show_frame 1
hc set frame_gap 2

# add overlapping window borders
hc set window_gap -3
hc set frame_padding 1
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1

# General
hc set focus_follows_mouse 1
hc set raise_on_click 1
hc set raise_on_focus 0

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod4
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Shift-Return spawn terminator
hc keybind $Mod-Shift-t spawn firefox
hc keybind $Mod-Shift-m spawn thunderbird
hc keybind $Mod-Shift-Escape spawn xscreensaver-command --lock
hc keybind $Mod-p spawn dmenu_run \
-i -nb "#000000" -nf white -sb "#1793D1" -sf white
hc keybind XF86AudioLowerVolume spawn ~/.config/herbstluftwm/volume.sh down
hc keybind XF86AudioRaiseVolume spawn ~/.config/herbstluftwm/volume.sh up
hc keybind XF86AudioMute spawn ~/.config/herbstluftwm/volume.sh mute
hc keybind Print spawn ~/bin/shoot
hc keybind $Mod-m set_layout max

hc keybind $Mod-semicolon spawn ~/.config/herbstluftwm/swap.sh auto
hc keybind $Mod-period spawn ~/.config/herbstluftwm/swap.sh terminator
hc keybind $Mod-slash spawn ~/.config/herbstluftwm/swap.sh close

# tags
hc rename default 1 || true
for i in {1..9}; do
    hc add $i
        hc keybind "$Mod-$i" use "$i"
        hc keybind "$Mod-Shift-$i" move "$i"
done

# GIMP
# ensure there is a gimp tag
hc add gimp
hc load gimp '
(split horizontal:0.850000:0
  (split horizontal:0.200000:1
    (clients vertical:0)
    (clients grid:0))
  (clients vertical:0))
'               # load predefined layout
# center all other gimp windows on gimp tag
hc rule class=Gimp tag=gimp index=01 pseudotile=on
hc rule class=Gimp windowrole~'gimp-(image-window|toolbox|dock)' \
    pseudotile=off
hc rule class=Gimp windowrole=gimp-toolbox focus=off index=00
hc rule class=Gimp windowrole=gimp-dock focus=off index=1

hc keybind $Mod-g use gimp
hc keybind $Mod-Shift-g move gimp

# cycle through tags
hc keybind $Mod-Shift-n use_index +1 --skip-visible
hc keybind $Mod-Shift-p  use_index -1 --skip-visible
hc keybind $Mod-Right use_index +1 --skip-visible
hc keybind $Mod-Left  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-u split vertical 0.5
hc keybind $Mod-o split horizontal 0.5
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-t pseudotile toggle

# resizing
RESIZESTEP=0.01
hc keybind $Mod-Control-h resize left +$RESIZESTEP
hc keybind $Mod-Control-j resize down +$RESIZESTEP
hc keybind $Mod-Control-k resize up +$RESIZESTEP
hc keybind $Mod-Control-l resize right +$RESIZESTEP

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 resize
hc mousebind $Mod-Button3 zoom

# focus
hc keybind $Mod-BackSpace   cycle_monitor
#hc keybind $Mod-Tab         cycle_all +1
#hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-Tab         cycle +1
hc keybind $Mod-Shift-Tab   cycle -1
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right
hc keybind $Mod-i jumpto urgent
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

# rules
hc unrule -F
hc rule focus=on # focus new clients

# normal stuff
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off
hc rule windowtype~'_NET_WM_STATE_FULLSCREEN' fullscreen=on

#hc rule class~'(Firefox.*|Vimperator.*|Nightly.*|Browser)' tag=2
#hc rule title='Nightly Updater' tag=2
hc rule instance~'(Mail.*|Thunderbird.*)' tag=4
hc rule class~'(Mail.*|Thunderbird.*)' tag=4
hc rule class='rdesktop' tag=6
hc rule class='vlc' tag=7 pseudotile=on

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
#hc auto_detect_monitors 1
#hc keybind $Mod-w focus_monitor 0
#hc keybind $Mod-e focus_monitor 1

# Set up multi monitors
while [[ $(hc list_monitors | wc -l) -gt 1 ]]; do
    hc remove_monitor 1
done

# tags
NUM_MONS=$(xrandr --current | grep "^\w.* connected" | wc -l)
MON_RES=( $(xrandr --current | grep "^\w.* connected" | awk '{print $3}') )
MON_NUMS=$( python2 -c "for i in range(${NUM_MONS}): print i" )

for i in ${MON_NUMS[@]} ; do
    echo "${i}"
    if [[ $i == '0' ]]; then
        hc move_monitor $i ${MON_RES[$i]};
    else
        hc add_monitor ${MON_RES[$i]};
    fi
done

#if [[ ${NUM_MONS} > 1 ]]; then
#    hc move_monitor 0 1366x768+0+0
#    hc add_monitor 1920x1080+1366+0
#else
#    hc move_monitor 0 1366x768+0+0
#fi

#for i in ${MON_NUMS[@]} ; do
#    if [[ $i == '0' ]]; then
#        hc move_monitor $i ${MON_RES[$i]};
#    else
#        hc add_monitor ${MON_RES[$i]};
#    fi
#done

killall panel.sh
# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    $panel $monitor &
done

